CREATE TABLE IF NOT EXISTS b_doweb_calc_standart
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	MATERIAL_NAME varchar(255) NULL,
	WIDTH_50 int(11) DEFAULT NULL,
    WIDTH_60 int(11) DEFAULT NULL,
    WIDTH_70 int(11) DEFAULT NULL,
    WIDTH_80 int(11) DEFAULT NULL,
    WIDTH_90 int(11) DEFAULT NULL,
    WIDTH_100 int(11) DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS b_doweb_calc_premium
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	MATERIAL_NAME varchar(255) NULL,
	WIDTH_50 int(11) DEFAULT NULL,
    WIDTH_60 int(11) DEFAULT NULL,
    WIDTH_70 int(11) DEFAULT NULL,
    WIDTH_80 int(11) DEFAULT NULL,
    WIDTH_90 int(11) DEFAULT NULL,
    WIDTH_100 int(11) DEFAULT NULL,
    PRIMARY KEY (ID)

);
CREATE TABLE IF NOT EXISTS b_doweb_calc_lux
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	MATERIAL_NAME varchar(255) NULL,
	WIDTH_50 int(11) DEFAULT NULL,
    WIDTH_60 int(11) DEFAULT NULL,
    WIDTH_70 int(11) DEFAULT NULL,
    WIDTH_80 int(11) DEFAULT NULL,
    WIDTH_90 int(11) DEFAULT NULL,
    WIDTH_100 int(11) DEFAULT NULL,
	PRIMARY KEY (ID)
);